# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "krakatoa-openx"
  s.version = "1.9.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Patterson", "Andy Smith", "TouchLocal P/L", "Dimitrij Denissenko"]
  s.date = "2012-12-26"
  s.description = "A Ruby interface to the OpenX XML-RPC API"
  s.email = "krakatoa1987@gmail.com"
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.txt",
    "Rakefile",
    "VERSION",
    "krakatoa-openx.gemspec",
    "lib/openx.rb",
    "lib/openx/image.rb",
    "lib/openx/invocation.rb",
    "lib/openx/persistance.rb",
    "lib/openx/services.rb",
    "lib/openx/services/advertiser.rb",
    "lib/openx/services/agency.rb",
    "lib/openx/services/banner.rb",
    "lib/openx/services/base.rb",
    "lib/openx/services/campaign.rb",
    "lib/openx/services/channel.rb",
    "lib/openx/services/publisher.rb",
    "lib/openx/services/session.rb",
    "lib/openx/services/zone.rb",
    "lib/openx/targeting_rule.rb",
    "lib/openx/targeting_rules.rb",
    "lib/openx/xmlrpc_client.rb",
    "test/assets/300x250.jpg",
    "test/assets/cat.swf",
    "test/helper.rb",
    "test/test_advertiser.rb",
    "test/test_agency.rb",
    "test/test_banner.rb",
    "test/test_base.rb",
    "test/test_campaign.rb",
    "test/test_channel.rb",
    "test/test_openx.rb",
    "test/test_publisher.rb",
    "test/test_services.rb",
    "test/test_session.rb",
    "test/test_targeting_rule.rb",
    "test/test_targeting_rules.rb",
    "test/test_xmlrpc_client.rb",
    "test/test_xmlrpc_session_client.rb",
    "test/test_zone.rb"
  ]
  s.homepage = "http://github.com/krakatoa/openx"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby interface to the OpenX XML-RPC API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

